name: Packer build Hetzner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        id: setup
        with:
          version: 1.10.3

      - name: Export HCLOUD_TOKEN
        run: echo "HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}" >> $GITHUB_ENV

      - name: Run `packer init`
        id: init
        run: packer init hetzner.pkr.hcl

      - name: Run `packer build`
        id: build
        run: packer build -var glueops_codespaces_container_tag=v0.48.0 -var version=v0.8.0 hetzner.pkr.hcl
