# This is a basic workflow to help you get started with Actions

name: Packer build AMI for Cloud Development Environment

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@v3.1.0
        id: setup
        with:
          version: 1.10.3

      - name: Run `packer init`
        id: init
        run: packer init aws.pkr.hcl

      - name: Run `packer build`
        id: build
        run: packer build -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} -var glueops_codespaces_container_tag=v0.42.0 aws.pkr.hcl
