# This is a basic workflow to help you get started with Actions

name: Packer build AMI for Cloud Development Environment

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.9.4

      - name: Run `packer init`
        id: init
        run: packer init aws.pkr.hcl

      - name: Run `packer build`
        id: build
        run: packer build -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} -var glueops_codespaces_container_tag=v0.34.0 aws.pkr.hcl
