# This is a basic workflow to help you get started with Actions

name: Packer build AMI for Cloud Development Environment

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        id: setup
        with:
          version: 1.10.3

      - name: Run `packer init`
        id: init
        run: packer init aws.pkr.hcl

      - name: Run `packer build`
        id: build
        run: packer build -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} -var glueops_codespaces_container_tag=v0.48.0 aws.pkr.hcl
