# This is a basic workflow to help you get started with Actions

name: Packer build AMI for Cloud Development Environment

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.9.4

      - name: Run `packer init`
        id: init
        run: packer init aws.pkr.hcl

      - name: Run `packer build`
        id: build
        run: packer build -var aws_access_key=${{ secrets.aws_access_key }} -var aws_secret_key=${{ secrets.aws_secret_key }} -var glueops_codespaces_container_tag=v0.32.0-alpha4 aws.pkr.hcl
